.TH DEVA-VISIBILITY 1 "15 January 2018" "DEVA Project"
.SH NAME
deva-visibility \- estimate locations of potential low-vision hazards
.SH SYNOPSIS
\." \fBdeva-visibility\fR \fB\-\-mild|\-\-moderate|\-\-significant|\-\-severe\fR
.TP
\fBdeva-visibility\fR \fIpreset-option\fR {\fIinput.hdr\fR | \-} \fIcoordinates\fR
\fIxyz.txt\fR \fIdist.txt\fR \fInor.txt\fR
\fIsimulated-view.hdr\fR \fIhazards.png\fR
.PP
				or
.TP
\fBdeva-visibility\fR [\fIoptions\fR] \fIacuity contrast\fR {\fIinput.hdr\fR | \-} \fIcoordinates\fR
\fIxyz.txt\fR \fIdist.txt\fR \fInor.txt\fR
\fIsimulated-view.hdr\fR \fIhazards.png\fR
.SH DESCRIPTION
Extends functionality of \fBdeva-filter\fR to provide estimates of
likely low-vision hazards, defined as geometric structures that may be a
mobility hazard but are not co-located with detectable visual contrast.
Two output images are created.  One is the same Radiance HDR format
image that would be created by \fBdeva-filter\fR, given comparable
arguments.  The other is a color PNG image, with estimated visibility
hazards shown in red and other geometric features estimated to be less
of a potential visibility hazard shown in dark gray.
.PP
.SH OPTIONS
All of the \fBdeva-filter\fR options, plus:
.TP
\fB\-\-luminanceboundaries==\fI<filename>.png\fR
Write a grayscale PNG image file indicating the location of detected
luminance boundaries.
.TP
\fB\-\-luminanceboundaries==\fI<filename>.png\fR
Write a grayscale PNG image file indicating the location of detected
luminance boundaries.
.SH ARGUMENTS
.TP
\fIinput.hdr\fR
Original Radiance image of area in design model to be evaluated for
low-vision visibility hazards, as for \fBdeva-filter\fR.
.TP
\fIcoordinates\fR
A two line text file.  The first line specifies the units for the
\fIxyz.txt\fR and \fIdist.txt\fR files. The second line is the same as
the VIEW record in \fIinput.hdr\fR.  See \fBmake-coordinates-file\fR for
information on how to create this file.
.TP
\fIxyz.txt\fR
A Radiance ASCII format file specifying the xyz model coordinates for
each surface point in the model corresponding to the line of sight
associated with each pixel in \fIinput.hdr\fR.
.TP
\fIdist.txt\fR
A Radiance ASCII format file specifying the distance from the viewpoint
to each surface point in the model corresponding to the line of sight
associated with each pixel in \fIinput.hdr\fR.
.TP
\fInor.txt\fR
A Radiance ASCII format file specifying the surface normal in model
coordinates for each surface point in the model corresponding to the
line of sight associated with each pixel in \fIinput.hdr\fR.  Note that
the numeric values are unitless since they specify a unit normal.
.TP
\fIsimulated-view.hdr\fR
A Radiance image simulating the reduced visibility associated with loss
of visual acuity and contrast sensitivity.
.TP
\fIhazards.png\fR
An output PNG image indicating likely potential visibility hazards.
.\" SH EXAMPLES
\." SH LIMITATIONS
\." PP
.SH AUTHOR
William B. Thompson
