#! /bin/sh

man -t ./deva-filter.1 | ps2pdf - deva-filter.pdf
man -t ./deva-visibility.1 | ps2pdf - deva-visibility.pdf
man -t ./make-coordinates-file.1 | ps2pdf - make-coordinates-file.pdf
man -t ./deva-visualize-geometry.1 | ps2pdf - deva-visualize-geometry.pdf
