#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include "devas-image.h"
#include "devas-canny.h"
#include "radianceIO.h"
#include "devas-png.h"
#include "devas-license.h"	/* DeVAS open source license */

#define	CANNY_ST_DEV	M_SQRT2
#define EPSILON		0.1

char	*progname;	/* one radiance routine requires this as a global */

char	*Usage = "luminance-boundaries input.hdr output.png";
int	args_needed = 2;

int
main ( int argc, char *argv[] )
{
    DeVAS_float_image	*input_image = NULL;	/* Y values in cd/m^2 */
    DeVAS_xyY_image	*input_image_xyY;	/* Y values in cd/m^2 */
    int			row, col;
    DeVAS_gray_image	*output_image = NULL;
    int			argpt = 1;

    /* scan and collect option flags */
    while ( ( ( argc - argpt ) >= 1 ) && ( argv[argpt][0] == '-' ) ) {
	if ( ( strcasecmp ( argv[argpt], "--nonargument" ) == 0 ) ||
		( strcasecmp ( argv[argpt], "-nonargument" ) == 0 ) ) {
	    exit ( EXIT_FAILURE );
	    argpt++;
	} else {
	    fprintf ( stderr, "%s: invalid flag (%s)!\n", progname,
		    argv[argpt] );
	    return ( EXIT_FAILURE );    /* error exit */
	}
    }

    if ( ( argc - argpt ) != args_needed ) {
	fprintf ( stderr, "%s\n", Usage );
	return ( EXIT_FAILURE );    /* error exit */
    }

    fprintf ( stderr,
      "luminance-boundaries: Does not work well on input images generated by\n"
      "devas-filter, perhaps because of quantization noise in the low\n"
      "precision Radiance file format (Warning)!\n" );

    input_image_xyY = DeVAS_xyY_image_from_radfilename ( argv[argpt++] );
    input_image =
	DeVAS_float_image_new ( DeVAS_image_n_rows ( input_image_xyY ),
	    DeVAS_image_n_cols ( input_image_xyY ) );

    for ( row = 0; row < DeVAS_image_n_rows ( input_image_xyY ); row++ ) {
	for ( col = 0; col < DeVAS_image_n_cols ( input_image_xyY ); col++ ) {
	    DeVAS_image_data ( input_image, row, col ) =
		DeVAS_image_data ( input_image_xyY, row, col ).Y;
	}
    }

    output_image = devas_canny_autothresh ( input_image, CANNY_ST_DEV,
	    NULL, NULL );

    for ( row = 0; row < DeVAS_image_n_rows ( output_image ); row++ ) {
	for ( col = 0; col < DeVAS_image_n_cols ( output_image ); col++ ) {
	    if ( DeVAS_image_data ( output_image, row, col ) != 0 ) {
		DeVAS_image_data ( output_image, row, col ) = 255;
	    }
	}
    }

    DeVAS_gray_image_to_filename_png ( argv[argpt++], output_image );

    DeVAS_float_image_delete ( input_image );
    DeVAS_xyY_image_delete ( input_image_xyY );
    DeVAS_gray_image_delete ( output_image );

    return ( EXIT_SUCCESS );	/* normal exit */
}
