#! /bin/bash

./distclean	# This will remove Mac, Windows, and Linux builds, but
		# it's the most reliable way to insure that the CMake
		# caches are cleaned

# Build libfftw3f.a:

    cd external-libs/fftw-3.3.7

    ./configure \
       --host=x86_64-w64-mingw32 \
       --build=x86_64-suse-linux-gnu \
       --target=x86_64-w64-mingw32 \
       --prefix=$PWD/../windowsinstall \
       --with-our-malloc16 --with-windows-f77-mangling \
       --disable-shared --enable-static --enable-threads \
       --with-combined-threads --enable-sse2 \
       --with-incoming-stack-boundary=2 \
       --enable-float

    make
    make install
    cd ../..

# Build libz.a

    cd external-libs/zlib-1.2.11
    # use preconfigured Makefile
    make PREFIX=x86_64-w64-mingw32- -fwin32/Makefile.gcc
    make BINARY_PATH=$PWD/../windowsinstall/bin \
    	INCLUDE_PATH=$PWD/../windowsinstall/include \
    	LIBRARY_PATH=$PWD/../windowsinstall/lib64 \
	-fwin32/Makefile.gcc \
		install
    cd ../..

# Build libpng.a

    cd external-libs/libpng-1.6.34
    ./configure \
	--host=x86_64-w64-mingw32 \
	--build=x86_64-suse-linux-gnu \
	--target=x86_64-w64-mingw32 \
	--enable-static \
	--disable-shared \
	--prefix=$PWD/../windowsinstall \
	CPPFLAGS=-I$PWD/../windowsinstall/include \
	LDFLAGS=-L$PWD/../windowsinstall/lib64
    make
    make install
    cd ../..

# Build deva-filter.exe and deva-visibility.exe

    cd build-windows
    cmake -DCMAKE_TOOLCHAIN_FILE=../Windows-toolchain.cmake ..
    make
    cd ..
