.TH GEOMETRIC-BOUNDARIES 1 "02 July 2018" "DeVAS Project"
.SH NAME
geometric-boundaries \- calculate geometric boundaries
.SH SYNOPSIS
\fBgeometric-boundaries\fR \fIcoordinates\fR \fIxyz.txt\fR
\fIdist.txt\fR \fInor.txt\fR \fIoutput.png\fR
.SH DESCRIPTION
Calculate geometry boundaries as in \fBdevas-visibility\fR.
\fIcoordinates\fR is a DeVAS-style coordinates file as in
\fBdevas-visibility\fR.  The other input files are Radiance ASCII files
specifying position, distance, and surface normals.  Output is a PNG file
with luminance boundary elements having a value of 255 and all other
elements having a value of 0.
.SH AUTHOR
William B. Thompson
